### ISSUE TITLE
Collect materials and references

### ISSUE THREAD

**Issue by Najma-Shakirah** [fiqdanish/Group-8-SAD#1]

**Comment by Najma-Shakirah** [comment]
Hi, aku rasa https://www.geeksforgeeks.org/software-engineering-prototyping-model/ boleh jadi macam outline/idea untuk apa kita nak tulis

**Comment by Najma-Shakirah** [comment]
https://drive.google.com/file/d/1EEoxSnAd8Jgdk4uruqrEoTrHa2vbSBsc/view?usp=drive_link

**Comment by Najma-Shakirah** [comment]
https://www.researchgate.net/publication/373800862_Software_Development_Life_Cycle_SDLC_Methodologies_for_Information_Systems_Project_Management

Hossain, Mohammad. (2023). Software Development Life Cycle (SDLC) Methodologies for Information Systems Project Management. 10.36948/ijfmr.2023.v05i05.6223.

**Comment by Najma-Shakirah** [comment]
![Image](https://github.com/fiqdanish/Group-8-SAD/assets/147504144/7e6a26dc-64d0-441a-b993-d63759082081)

**Comment by Najma-Shakirah** [comment]
https://arxiv.org/pdf/1612.03707 example ieee short paper

**Comment by Najma-Shakirah** [comment]
Senarath, Udesh S. "Waterfall methodology, prototyping and agile development." Tech. Rep. (2021): 1-16.
https://www.researchgate.net/profile/Udesh-S-Senarath/publication/353324450_Waterfall_Methodology_Prototyping_and_Agile_Development/links/60f41f71fb568a7098b9d035/Waterfall-Methodology-Prototyping-and-Agile-Development.pdf

**Comment by nawwarahauni** [comment]
Alazzawi, A., & Rahmatullah, B. (2023). A Comprehensive Review of Software Development Life Cycle methodologies: Pros, Cons, and Future Directions. Iraqi Journal For Computer Science and Mathematics, 4(4), 173-190. https://www.iasj.net/iasj/download/7e28313890452e4f
